name = "InfiniteRandomArrays"
uuid = "2bc77966-89c7-476d-a40f-269028fac4a9"
authors = ["DanielVandH <danj.vandenheuvel@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
