name = "InfiniteRandomArrays"
uuid = "2bc77966-89c7-476d-a40f-269028fac4a9"
authors = ["DanielVandH <danj.vandenheuvel@gmail.com> and contributors"]
version = "1.0.0"

[deps]
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
InfiniteArrays = "0.14"
LazyArrays = "2"
Random = "1"
Test = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
